[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
liquid_staking = "4fLrcA8T6sH1z691Rv4JubkzqoNq9fjooaw4iKfjXzj3"

[programs.localnet]
liquid_staking = "4fLrcA8T6sH1z691Rv4JubkzqoNq9fjooaw4iKfjXzj3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
